val:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    ihmc_valkyrie_control_java_bridge:
        jvm_args: "-Djava.class.path=/home/jesper/valkyrie/ValkyrieController.jar"
        main_class: us.ihmc.valkyrieRosControl.ValkyrieRosControlSliderBoard
        working_dir: /home/jesper/valkyrie/
        type: ihmc_ros_control/IHMCValkyrieControlJavaBridge


